#!/bin/bash
#
# Newznab scheduler service
#
# chkconfig: 2345 08 92
# description:  Starts, stops Newznab import
#
### BEGIN INIT INFO
# Provides: newznab
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop Newznab
# Description: Start, stop Newznab
### END INIT INFO

# Source function library.
. /etc/init.d/functions

# only usable for root
[ $EUID = 0 ] || exit 4

scriptfile="/opt/newznab/misc/update_scripts/nix_scripts/newznab_centos.sh"
pidfile="/var/run/newznab.pid"

start() {

        $scriptfile &
        ps aux|grep newznab_centos.sh|grep -v grep|awk '{print $2}' > $pidfile

    return $ret
}

stop() {
        kill -9 `cat $pidfile`
}

restart() {
    stop
    start
}

